#include "final3.h"

electric_car::electric_car(std::string _VIN,
                           std::string _County,
                           std::string _City,
                           std::string _State,
                           double _PostalCode,
                           double _ModelYear,
                           std::string _Make,
                           std::string _Model,
                           std::string _ElectricVehicleType,
                           std::string _CleanAlternativeFuelVehicleEligbility,
                           double _ElectricRange,
                           double _BaseMSPR,
                           double _LegislativeDistric,
                           double _DOLVehicleID,
                           std::string _VehicleLocation,
                           std::string _ElectricUtility,
                           double _CensusTract)
    : VIN(_VIN),
      County(_County),
      City(_City),
      State(_State),
      PostalCode(_PostalCode),
      ModelYear(_ModelYear),
      Make(_Make),
      Model(_Model),
      ElectricVehicleType(_ElectricVehicleType),
      CleanAlternativeFuelVehicleEligbility(_CleanAlternativeFuelVehicleEligbility),
      ElectricRange(_ElectricRange),
      BaseMSPR(_BaseMSPR),
      LegislativeDistric(_LegislativeDistric),
      DOLVehicleID(_DOLVehicleID),
      VehicleLocation(_VehicleLocation),
      ElectricUtility(_ElectricUtility),
      CensusTract(_CensusTract){};